// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/25/2024, 8:22:01 PM
const configMerger = require("/Users/macmarek/Desktop/vehis-calculator/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/macmarek/Desktop/vehis-calculator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/plugins/**/*.{js,ts,mjs}","/Users/macmarek/Desktop/vehis-calculator/composables/**/*.{js,ts,mjs}","/Users/macmarek/Desktop/vehis-calculator/utils/**/*.{js,ts,mjs}","/Users/macmarek/Desktop/vehis-calculator/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macmarek/Desktop/vehis-calculator/app.config.{js,ts,mjs}"] }));

module.exports = config
